### ISSUE TITLE
'Please specify a qConfig global variable' error

### ISSUE THREAD

**Issue by miranda-elliott** [qlik-demo-team/qdt-vue-template#2]
When I edit this template to connect to my own app and embed an object, in place of the chart it shows the text error: `Please specify a qConfig global variable`. All I changed was the host, prefix, and app id in QdtComponent.vue and the object id in EmbedObject.vue. There aren't any errors in the console. I've attached a screenshot. What does this mean and how can it be resolved? 

![Screenshot](https://user-images.githubusercontent.com/8364014/44428139-79e10180-a561-11e8-817a-8caefb04760b.png)

**Comment by yianni-ververis** [comment]
Hello Miranda,

Make sure your prefix is your virtual proxy, if its the default it should be empty like prefix:"", also make sure you are initiating the class only once.

Can you send me the QdtComponent.vue?
https://github.com/qlik-demo-team/qdt-vue-template/blob/master/src/components/QdtComponent.vue

**Comment by miranda-elliott** [comment]
The prefix is my virtual proxy (named test). I'm only initiating the class in QdtComponent,vue. 

Here's that file: 
[QdtComponent.vue](https://github.com/qlik-demo-team/qdt-vue-template/files/2310393/QdtComponent.vue.txt)

Thanks for your help!

**Comment by yianni-ververis** [comment]
I would also make sure that your localhost with your port is whitelisted in the  virtual proxy

Sent from my iPhone
________________________________

**Comment by miranda-elliott** [comment]
I changed the prefix to "test" (no slashes) in QdtComponent.vue and "localhost" to "http://localhost:8080" in the virtual proxy whitelist. I'm no longer having the same error, it seems like it's actually attempting to connect now. However, it's failing to connect and showing an error modal I've attached a screenshot of. 

![qlik sense error](https://user-images.githubusercontent.com/8364014/44468886-3f747480-a5f4-11e8-9636-281ce35f530c.png)

**Comment by yianni-ververis** [comment]
Do you have tokens? Does anon have access to the stream where the app is ?

Sent from my iPhone
________________________________

**Comment by miranda-elliott** [comment]
I've been curious about authentication via headers and whether that would work for this case. Found a [thread on Qlik Community](https://community.qlik.com/thread/303358) asking a similar question about how to use auth headers with qdt-components but it doesn't have any answers.

**Comment by miranda-elliott** [comment]
Closing because the original issue was resolved. 

Opening an authentication specific issue on the qdt-components repo: [Issue #39 - Header authentication](https://github.com/qlik-demo-team/qdt-components/issues/39).
